"""
Hyper-Adapter Module — Module G
=================================

Hypernetwork that generates lightweight subject adapters from a subject
fingerprint. Supports LoRA injection, FiLM modulation, and multiple
adaptation modes from zero-shot to full fine-tuning.
"""

import logging
import math
from typing import Any, Dict, List, Optional, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import Tensor

logger = logging.getLogger(__name__)


class LoRAAdapter(nn.Module):
    """Low-Rank Adaptation layer (Hu et al., 2021).

    Adds a low-rank residual: output = W_orig @ x + alpha * (B @ A @ x)
    where A: (d_in, rank), B: (rank, d_out).

    Args:
        d_in: Input dimensionality.
        d_out: Output dimensionality.
        rank: LoRA rank.
        alpha: Scaling factor.
    """

    def __init__(self, d_in: int, d_out: int, rank: int = 8, alpha: float = 1.0):
        super().__init__()
        self.rank = rank
        self.alpha = alpha
        self.lora_A = nn.Parameter(torch.randn(d_in, rank) * (1.0 / math.sqrt(rank)))
        self.lora_B = nn.Parameter(torch.zeros(rank, d_out))

    def forward(self, x: Tensor) -> Tensor:
        """Compute LoRA residual.

        Args:
            x: Input tensor, shape (..., d_in).

        Returns:
            LoRA adjustment, shape (..., d_out).
        """
        return self.alpha * (x @ self.lora_A @ self.lora_B)


class FiLMLayer(nn.Module):
    """Feature-wise Linear Modulation (Perez et al., 2018).

    Applies affine transformation: output = gamma * x + beta
    where gamma and beta are generated by a conditioning network.

    Args:
        d_model: Feature dimensionality to modulate.
    """

    def __init__(self, d_model: int):
        super().__init__()
        self.d_model = d_model

    def forward(self, x: Tensor, gamma: Tensor, beta: Tensor) -> Tensor:
        """Apply FiLM modulation.

        Args:
            x: Input features, shape (..., d_model).
            gamma: Scale parameters, shape (B, d_model) or broadcastable.
            beta: Shift parameters, shape (B, d_model) or broadcastable.

        Returns:
            Modulated features, same shape as x.
        """
        if gamma.dim() < x.dim():
            for _ in range(x.dim() - gamma.dim()):
                gamma = gamma.unsqueeze(1)
                beta = beta.unsqueeze(1)
        return gamma * x + beta


class HyperNetwork(nn.Module):
    """Generates adapter parameters from a subject fingerprint.

    Produces LoRA weights or FiLM parameters for multiple target layers
    based on a compact subject fingerprint vector.

    Args:
        fingerprint_dim: Input fingerprint dimensionality.
        d_model: Target model dimensionality for adapters.
        n_target_layers: Number of transformer layers to adapt.
        adapter_type: Type of adapter to generate ('lora' or 'film').
        lora_rank: LoRA rank (only for adapter_type='lora').
        hidden_dim: Hidden dimension in the hypernetwork.
    """

    def __init__(
        self,
        fingerprint_dim: int = 128,
        d_model: int = 768,
        n_target_layers: int = 6,
        adapter_type: str = "film",
        lora_rank: int = 8,
        hidden_dim: int = 512,
    ):
        super().__init__()
        self.fingerprint_dim = fingerprint_dim
        self.d_model = d_model
        self.n_target_layers = n_target_layers
        self.adapter_type = adapter_type
        self.lora_rank = lora_rank

        # Shared feature extraction from fingerprint
        self.shared_encoder = nn.Sequential(
            nn.Linear(fingerprint_dim, hidden_dim),
            nn.GELU(),
            nn.LayerNorm(hidden_dim),
            nn.Linear(hidden_dim, hidden_dim),
            nn.GELU(),
            nn.LayerNorm(hidden_dim),
        )

        if adapter_type == "film":
            # Generate FiLM gamma/beta for each layer
            self.film_generators = nn.ModuleList([
                nn.Linear(hidden_dim, d_model * 2)
                for _ in range(n_target_layers)
            ])
            # Initialize to identity modulation
            for gen in self.film_generators:
                nn.init.zeros_(gen.weight)
                nn.init.zeros_(gen.bias)
                # Set bias so initial gamma=1, beta=0
                gen.bias.data[:d_model] = 1.0

        elif adapter_type == "lora":
            # Generate LoRA A and B matrices for each layer
            self.lora_generators = nn.ModuleList([
                nn.Sequential(
                    nn.Linear(hidden_dim, d_model * lora_rank + lora_rank * d_model),
                )
                for _ in range(n_target_layers)
            ])
            for gen in self.lora_generators:
                nn.init.zeros_(gen[-1].weight)
                nn.init.zeros_(gen[-1].bias)

        n_params = sum(p.numel() for p in self.parameters())
        logger.info(
            "HyperNetwork: fp_dim=%d, d_model=%d, layers=%d, type=%s, params=%d",
            fingerprint_dim, d_model, n_target_layers, adapter_type, n_params,
        )

    def forward(self, fingerprint: Tensor) -> Dict[str, Any]:
        """Generate adapter parameters from fingerprint.

        Args:
            fingerprint: Subject fingerprint, shape (B, fingerprint_dim).

        Returns:
            Dict with adapter parameters per layer:
                - For 'film': {'layer_{i}_gamma': (B, d_model), 'layer_{i}_beta': (B, d_model)}
                - For 'lora': {'layer_{i}_A': (B, d_in, rank), 'layer_{i}_B': (B, rank, d_out)}
        """
        B = fingerprint.shape[0]
        h = self.shared_encoder(fingerprint)  # (B, hidden_dim)
        adapters: Dict[str, Tensor] = {}

        if self.adapter_type == "film":
            for i, gen in enumerate(self.film_generators):
                params = gen(h)  # (B, 2*d_model)
                gamma = params[:, : self.d_model]
                beta = params[:, self.d_model :]
                adapters[f"layer_{i}_gamma"] = gamma
                adapters[f"layer_{i}_beta"] = beta

        elif self.adapter_type == "lora":
            for i, gen in enumerate(self.lora_generators):
                params = gen(h)  # (B, d_model*rank + rank*d_model)
                split_a = self.d_model * self.lora_rank
                a_flat = params[:, :split_a]
                b_flat = params[:, split_a:]
                adapters[f"layer_{i}_A"] = a_flat.view(B, self.d_model, self.lora_rank)
                adapters[f"layer_{i}_B"] = b_flat.view(B, self.lora_rank, self.d_model)

        adapters["fingerprint"] = fingerprint
        return adapters


class AdaptationController:
    """Controls which parameters are frozen/trainable for different adaptation modes.

    Modes:
        0: zero_shot - All frozen, only fingerprint-based hyper-adapter active.
        1: unsupervised_calibration - Fingerprint updated with unsupervised calibration data.
        2: supervised_fewshot - Adapter parameters trained on few labeled samples.
        3: adapter_only - Only adapter parameters and head fine-tuned.
        4: head_only - Only decoding heads fine-tuned.
        5: full_finetune - All parameters unfrozen.
    """

    MODES = [
        "zero_shot",
        "unsupervised_calibration",
        "supervised_fewshot",
        "adapter_only",
        "head_only",
        "full_finetune",
    ]

    def __init__(self, mode: str = "full_finetune"):
        if mode not in self.MODES:
            raise ValueError(f"Unknown adaptation mode: {mode}. Valid: {self.MODES}")
        self.mode = mode
        logger.info("AdaptationController: mode=%s", mode)

    def configure_trainable(
        self, model: nn.Module, hyper_network: Optional[nn.Module] = None
    ) -> List[nn.Parameter]:
        """Configure which parameters are trainable based on mode.

        Args:
            model: The NeuroBridgeOT model.
            hyper_network: Optional HyperNetwork module.

        Returns:
            List of trainable parameters for the optimizer.
        """
        # First freeze everything
        for param in model.parameters():
            param.requires_grad = False
        if hyper_network is not None:
            for param in hyper_network.parameters():
                param.requires_grad = False

        trainable = []

        if self.mode == "zero_shot":
            # Nothing trainable at inference time
            pass

        elif self.mode == "unsupervised_calibration":
            # Only fingerprint-related parameters
            if hyper_network is not None:
                for param in hyper_network.parameters():
                    param.requires_grad = True
                    trainable.append(param)

        elif self.mode == "supervised_fewshot":
            # Adapter + heads
            if hyper_network is not None:
                for param in hyper_network.parameters():
                    param.requires_grad = True
                    trainable.append(param)
            for name, param in model.named_parameters():
                if "head" in name or "adapter" in name:
                    param.requires_grad = True
                    trainable.append(param)

        elif self.mode == "adapter_only":
            # All adapter-related parameters + heads
            if hyper_network is not None:
                for param in hyper_network.parameters():
                    param.requires_grad = True
                    trainable.append(param)
            for name, param in model.named_parameters():
                if any(k in name for k in ["head", "adapter", "film", "lora", "fingerprint"]):
                    param.requires_grad = True
                    trainable.append(param)

        elif self.mode == "head_only":
            for name, param in model.named_parameters():
                if "head" in name:
                    param.requires_grad = True
                    trainable.append(param)

        elif self.mode == "full_finetune":
            for param in model.parameters():
                param.requires_grad = True
                trainable.append(param)
            if hyper_network is not None:
                for param in hyper_network.parameters():
                    param.requires_grad = True
                    trainable.append(param)

        n_trainable = sum(p.numel() for p in trainable)
        n_total = sum(p.numel() for p in model.parameters())
        logger.info(
            "Adaptation mode=%s: %d/%d params trainable (%.1f%%)",
            self.mode, n_trainable, n_total, 100.0 * n_trainable / max(n_total, 1),
        )
        return trainable
