name = "FMRIDecoding"
version = "0.1.0"
defaultTargets = ["FMRIDecoding"]

[[require]]
name = "mathlib"
from = "git"
url = "https://github.com/leanprover-community/mathlib4"
rev = "v4.14.0"

[[lean_lib]]
name = "FMRIDecoding"
